Fix inconsistency when build both shared/static lib
open-source-parsers/jsoncpp pull request #1214
Opened 2020-09-02 03:26 UTC by dota17

Hi @SpaceIm please check this patch if it solves your issue.

2020-11-04 05:48 UTC, xkszltl requested changes

2020-11-04 05:48 UTC, xkszltl commented on src/lib_json/CMakeLists.txt
>      # avoid name clashes on windows as the shared import lib is alse named jsoncpp.lib
typo: alse -> also

2020-11-04 05:48 UTC, xkszltl commented on src/lib_json/CMakeLists.txt
> +        OUTPUT_NAME jsoncpp
I would recommend to keep them different (and consistent across versions) to support packaging of dual (shared+static) build.
As you may noticed MSVC generates import lib (`.lib`) for `.dll`, which should not be confused with static `.lib`.

2020-11-04 05:48 UTC, xkszltl commented on src/lib_json/CMakeLists.txt
> +        set(STATIC_LIB ${PROJECT_NAME}_static)
You can `add_library(<default name> ALIAS jsoncpp_static)` or `add_library(<default name> INTERFACE)` and them `target_link_libraries(<default name> INTERFACE jsoncpp_static)

2024-09-12 00:37 UTC, baylesj commented
Closing this due to inactivity. Feel free to reopen if you are able to address feedback.

2024-09-12 00:37 UTC, closed without merging